export const categoryIcons = [
  { id: "web", value: "🌐", label: "Web (🌐)" },
  { id: "mobile", value: "📱", label: "Mobile (📱)" },
  { id: "components", value: "🧩", label: "Components (🧩)" },
  { id: "dashboard", value: "📊", label: "Dashboard (📊)" },
  { id: "e-commerce", value: "🛒", label: "E-commerce (🛒)" },
  { id: "landing", value: "🎯", label: "Landing (🎯)" },
  { id: "backend", value: "⚙️", label: "Backend (⚙️)" },
  { id: "analytics", value: "📈", label: "Analytics (📈)" },
  { id: "design", value: "🎨", label: "Design (🎨)" },
  { id: "tools", value: "🔧", label: "Tools (🔧)" },
  { id: "education", value: "📚", label: "Education (📚)" },
  { id: "games", value: "🎮", label: "Games (🎮)" },
  { id: "security", value: "🔒", label: "Security (🔒)" },
  { id: "cloud", value: "☁️", label: "Cloud (☁️)" },
  { id: "ai/ml", value: "🤖", label: "AI/ML (🤖)" },
  { id: "mobile app", value: "📲", label: "Mobile App (📲)" },
  { id: "desktop", value: "💻", label: "Desktop (💻)" },
  { id: "global", value: "🌍", label: "Global (🌍)" },
  { id: "startup", value: "🚀", label: "Startup (🚀)" },
  { id: "enterprise", value: "🏢", label: "Enterprise (🏢)" },
];

