export const technologyIcons = [
  { id: "react", value: "⚛️", label: "React (⚛️)" },
  { id: "nextjs", value: "▲", label: "Next.js (▲)" },
  { id: "typescript", value: "🔷", label: "TypeScript (🔷)" },
  { id: "css", value: "🎨", label: "CSS/Design (🎨)" },
  { id: "nodejs", value: "🟢", label: "Node.js (🟢)" },
  { id: "python", value: "🐍", label: "Python (🐍)" },
  { id: "java", value: "☕", label: "Java (☕)" },
  { id: "postgresql", value: "🐘", label: "PostgreSQL (🐘)" },
  { id: "mongodb", value: "🍃", label: "MongoDB (🍃)" },
  { id: "docker", value: "🐳", label: "Docker (🐳)" },
  { id: "cloud", value: "☁️", label: "Cloud (☁️)" },
  { id: "tools", value: "🔧", label: "Tools (🔧)" },
  { id: "mobile", value: "📱", label: "Mobile (📱)" },
  { id: "games", value: "🎮", label: "Games (🎮)" },
  { id: "ai-ml", value: "🤖", label: "AI/ML (🤖)" },
  { id: "performance", value: "⚡", label: "Performance (⚡)" },
  { id: "database", value: "🗄️", label: "Database (🗄️)" },
  { id: "api", value: "🔌", label: "API (🔌)" },
  { id: "testing", value: "🧪", label: "Testing (🧪)" },
  { id: "security", value: "🔒", label: "Security (🔒)" },
  { id: "devops", value: "⚙️", label: "DevOps (⚙️)" },
  { id: "frontend", value: "💻", label: "Frontend (💻)" },
  { id: "backend", value: "🖥️", label: "Backend (🖥️)" },
  { id: "fullstack", value: "🚀", label: "Full Stack (🚀)" },
  { id: "blockchain", value: "⛓️", label: "Blockchain (⛓️)" },
  { id: "iot", value: "🌐", label: "IoT (🌐)" },
  { id: "vr-ar", value: "🥽", label: "VR/AR (🥽)" },
  { id: "machine-learning", value: "🧠", label: "Machine Learning (🧠)" },
  { id: "data-science", value: "📊", label: "Data Science (📊)" },
  { id: "microservices", value: "🔗", label: "Microservices (🔗)" },
];
